#!/usr/bin/env python3
"""
RYZE.ai Full Demo Seed Script
Adds comprehensive demo data: 22 candidates, 12 employers, 18 job orders,
30 bookings with meeting summaries, 5 chat sessions, 10 waitlist entries.

Run from the project root:
    python seed_full.py

Safe to run on existing data — adds records, does not delete anything.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from datetime import date, datetime, timedelta
from app.core.database import SessionLocal
from app.models.candidate import Candidate
from app.models.employer_profile import EmployerProfile
from app.models.job_order import JobOrder
from app.models.booking import Booking
from app.models.chat_session import ChatSession
from app.models.chat_message import ChatMessage

db = SessionLocal()
today = date.today()

def d(days_ago): return today - timedelta(days=days_ago)
def dt(days_ago, hour=10): return datetime(today.year, today.month, today.day, hour, 0) - timedelta(days=days_ago)


# ── Candidates (22) ────────────────────────────────────────────────────────
print("Seeding candidates...")

candidates = [
    Candidate(
        name="Sarah Chen", email="schen@gmail.com", phone="617-555-0101",
        current_title="Senior Accountant", current_company="MedBridge Health",
        location="Boston, MA", linkedin_url="https://linkedin.com/in/sarahchen",
        ai_career_level="mid", ai_years_experience=5,
        ai_certifications="CPA",
        ai_summary="Big 4-trained senior accountant at a Boston healthcare company. Strong NetSuite skills, healthcare industry background, and a clear desire to grow into an Accounting Manager or Controller track role. Very polished communicator.",
        ai_experience="PwC (2019–2022) — audit associate, healthcare clients. MedBridge Health (2022–present) — senior accountant, owns the monthly close, manages 2 staff accountants.",
        ai_education="BS Accounting, Boston University, 2019",
        ai_skills=["NetSuite", "Healthcare", "GAAP", "SOX", "Close Management", "Big 4"],
        ai_years_experience=5, notes="Great first call. Interested in Controller track. Target $95–110K. Hybrid preferred.",
    ),
    Candidate(
        name="Michael Torres", email="mtorres@gmail.com", phone="617-555-0102",
        current_title="Controller", current_company="Apex Manufacturing",
        location="Waltham, MA",
        ai_career_level="senior", ai_years_experience=12,
        ai_certifications="CPA",
        ai_summary="Seasoned Controller with 12 years in manufacturing and PE-backed environments. Owns the full close cycle, managed a team of 8, and led an ERP migration from QuickBooks to NetSuite. Ready for a CFO role or VP Finance at a mid-market company.",
        ai_experience="Grant Thornton (2012–2016) — audit senior, manufacturing. Apex Manufacturing (2016–present) — Controller, $120M revenue, PE-backed.",
        ai_education="MS Accounting, Northeastern, 2012",
        ai_skills=["Manufacturing", "PE-backed", "NetSuite", "ERP Migration", "Team Management", "CPA"],
        notes="Passive candidate. Target $160–180K. Open to right opportunity.",
    ),
    Candidate(
        name="Jennifer Walsh", email="jwalsh@gmail.com", phone="617-555-0103",
        current_title="Audit Manager", current_company="Deloitte",
        location="Boston, MA",
        ai_career_level="senior", ai_years_experience=9,
        ai_certifications="CPA",
        ai_summary="Big 4 audit manager at Deloitte with 9 years specializing in life sciences and biotech clients. Strong technical accounting, extensive experience with SEC reporting and IPO readiness. Looking to transition to a Director of Finance or VP role in industry.",
        ai_experience="Deloitte (2015–present) — staff to manager. Life sciences portfolio. Led 4 public company audits.",
        ai_education="BS Accounting, BC, 2015",
        ai_skills=["Big 4", "Life Sciences", "SEC Reporting", "IPO Readiness", "GAAP", "IFRS"],
        notes="Ready to make the move to industry. Target $130–150K. Downtown Boston preferred.",
    ),
    Candidate(
        name="David Kim", email="dkim@gmail.com", phone="617-555-0104",
        current_title="FP&A Manager", current_company="CloudMetrics Inc",
        location="Cambridge, MA",
        ai_career_level="senior", ai_years_experience=8,
        ai_summary="FP&A Manager at a 200-person SaaS company. Owns the annual budget ($45M), monthly reporting package, and investor KPI deck. Expert in ARR, CAC, LTV, and cohort analysis. Adaptive Insights certified.",
        ai_experience="Bain & Company (2016–2019) — financial analyst. CloudMetrics (2019–present) — FP&A Manager.",
        ai_education="MBA, MIT Sloan, 2016; BS Finance, UMass, 2013",
        ai_skills=["FP&A", "SaaS Metrics", "ARR", "CAC", "LTV", "Adaptive Insights", "Modeling"],
        notes="Strong quantitative background. Target $125–145K.",
    ),
    Candidate(
        name="Amanda Foster", email="afoster@gmail.com", phone="617-555-0105",
        current_title="Accounting Manager", current_company="Harbor Logistics",
        location="Quincy, MA",
        ai_career_level="mid", ai_years_experience=6,
        ai_certifications="CPA",
        ai_summary="Accounting Manager at a regional logistics company, overseeing a team of 4 staff accountants. Strong close management, fixed assets, and lease accounting (ASC 842). Looking to step into a Controller role at a smaller company.",
        ai_experience="KPMG (2018–2021) — audit associate. Harbor Logistics (2021–present) — Accounting Manager.",
        ai_education="BS Accounting, UNH, 2018",
        ai_skills=["ASC 842", "Fixed Assets", "Close Management", "GAAP", "Team Leadership"],
        notes="Ready for Controller role. Target $110–125K. South Shore preferred.",
    ),
    Candidate(
        name="Robert Huang", email="rhuang@gmail.com", phone="617-555-0106",
        current_title="CFO", current_company="Atlantic Distribution Co",
        location="Boston, MA",
        ai_career_level="executive", ai_years_experience=20,
        ai_certifications="CPA, CFA",
        ai_summary="CFO with 20 years spanning public accounting, PE-backed, and public company environments. Built two finance teams from scratch, led $300M acquisition integration, and managed relationships with PE sponsors and public market investors. Open to CFO or fractional CFO opportunities.",
        ai_experience="EY (2004–2009). Atlantic Distribution (2009–2018) — VP Finance then CFO. Board advisor (2018–present).",
        ai_education="MBA, Wharton, 2004; BS Accounting, Cornell, 2001",
        ai_skills=["CFO", "M&A", "PE-backed", "Capital Markets", "Investor Relations", "FP&A"],
        notes="Exploring next chapter. Open to CFO or board roles. Target $250K+.",
    ),
    Candidate(
        name="Lisa Martinez", email="lmartinez@gmail.com", phone="617-555-0107",
        current_title="Staff Accountant", current_company="ClearPath Health",
        location="Somerville, MA",
        ai_career_level="junior", ai_years_experience=2,
        ai_summary="Junior staff accountant at a healthcare startup with 2 years experience. Recent CPA exam candidate. Strong Excel skills, experience with Sage Intacct, and a strong work ethic. Looking for her first step up to a senior accountant role.",
        ai_experience="Ernst & Young internship (2022). ClearPath Health (2022–present) — staff accountant.",
        ai_education="BS Accounting, Bentley, 2022",
        ai_skills=["Sage Intacct", "Excel", "Healthcare", "Month-end Close", "AP/AR"],
        notes="Strong upside candidate. Target $65–75K.",
    ),
    Candidate(
        name="James O'Brien", email="jobrien@gmail.com", phone="617-555-0108",
        current_title="Tax Manager", current_company="PwC",
        location="Boston, MA",
        ai_career_level="senior", ai_years_experience=10,
        ai_certifications="CPA",
        ai_summary="Tax Manager at PwC with 10 years specializing in corporate tax, SALT, and M&A transaction advisory. Managed a book of 25+ clients across manufacturing, tech, and financial services. Ready to move to an in-house Director of Tax or VP Tax role.",
        ai_experience="PwC (2014–present) — associate to manager, tax services group.",
        ai_education="MS Taxation, Bentley, 2014; BS Accounting, BC, 2012",
        ai_skills=["Corporate Tax", "SALT", "M&A Tax", "ASC 740", "Tax Provision", "Big 4"],
        notes="Motivated by the in-house move. Target $150–170K.",
    ),
    Candidate(
        name="Emily Rodriguez", email="erodriguez@gmail.com", phone="617-555-0109",
        current_title="Director of Finance", current_company="Vertex Pharma",
        location="Boston, MA",
        ai_career_level="executive", ai_years_experience=14,
        ai_certifications="CPA",
        ai_summary="Director of Finance at a major biotech, overseeing $800M in revenue operations. Deep experience with clinical trial accounting, cost allocation, and FDA milestone accounting. Positioned for VP Finance or CFO at a mid-size biotech.",
        ai_experience="Deloitte (2010–2014). Various biotech roles (2014–present). Vertex (2020–present) — Director of Finance.",
        ai_education="MBA, Harvard Business School, 2010; BS Accounting, Tufts, 2007",
        ai_skills=["Biotech", "Clinical Trial Accounting", "ASC 805", "Mergers", "Board Reporting"],
        notes="Not actively looking but open to the right CFO role. Target $200K+.",
    ),
    Candidate(
        name="Marcus Rivera", email="mrivera@gmail.com", phone="617-555-0110",
        current_title="Senior Accountant", current_company="Deloitte",
        location="Boston, MA",
        ai_career_level="mid", ai_years_experience=4,
        ai_certifications="CPA",
        ai_summary="Big 4 senior accountant at Deloitte, focused on financial services clients. Strong technical accounting skills, SOX experience, and a clear desire to move to industry. Would make an excellent Senior or Accounting Manager at a financial services or asset management firm.",
        ai_experience="Deloitte (2020–present) — associate to senior, financial services.",
        ai_education="BS Accounting, Villanova, 2020",
        ai_skills=["Financial Services", "SOX", "Big 4", "GAAP", "Consolidations", "Revenue Recognition"],
        notes="Ready to make the move. Target $90–105K.",
    ),
    Candidate(
        name="Rachel Green", email="rgreen@gmail.com", phone="617-555-0111",
        current_title="Controller", current_company="Bloom Retail Group",
        location="Newton, MA",
        ai_career_level="senior", ai_years_experience=11,
        ai_certifications="CPA",
        ai_summary="Controller at a PE-backed retail company managing $90M in revenue and a team of 6. Strong expertise in retail accounting, inventory management, and multi-location consolidations. Ready for a VP Finance or divisional CFO role.",
        ai_experience="RSM (2013–2017). Bloom Retail (2017–present) — Senior Accountant to Controller.",
        ai_education="BS Accounting, Babson, 2013",
        ai_skills=["Retail", "Inventory Accounting", "Consolidations", "PE-backed", "NetSuite"],
        notes="Open to VP Finance or divisional CFO. Target $165–185K.",
    ),
    Candidate(
        name="Thomas Anderson", email="tanderson@gmail.com", phone="617-555-0112",
        current_title="FP&A Analyst", current_company="Launchpad AI",
        location="Cambridge, MA",
        ai_career_level="junior", ai_years_experience=2,
        ai_summary="Junior FP&A analyst at an early-stage AI startup. Excel modeling, Tableau dashboards, and board deck preparation. Strong financial modeling skills for someone early in their career. CPA exam in progress.",
        ai_experience="Intern at Fidelity (2022). Launchpad AI (2022–present).",
        ai_education="BS Finance, Northeastern, 2022",
        ai_skills=["FP&A", "Excel", "Tableau", "Financial Modeling", "SaaS", "Startup"],
        notes="Strong upside. Target $70–80K.",
    ),
    Candidate(
        name="Nicole Williams", email="nwilliams@gmail.com", phone="617-555-0113",
        current_title="Accounting Manager", current_company="Summit CPA Group",
        location="Boston, MA",
        ai_career_level="mid", ai_years_experience=7,
        ai_certifications="CPA",
        ai_summary="Public accounting manager at a regional CPA firm with 7 years serving closely-held business clients. Broad technical skills across tax, audit, and advisory. Considering a move to private industry for better work-life balance. Would be a strong Senior Accountant or Accounting Manager in industry.",
        ai_experience="Summit CPA Group (2017–present) — staff to manager.",
        ai_education="BS Accounting, Providence College, 2017",
        ai_skills=["Public Accounting", "Tax", "Audit", "QuickBooks", "Advisory", "Small Business"],
        notes="Motivated by W/L balance. Target $100–115K.",
    ),
    Candidate(
        name="Kevin Park", email="kpark@gmail.com", phone="617-555-0114",
        current_title="VP Finance", current_company="Granite Biotech",
        location="Lexington, MA",
        ai_career_level="executive", ai_years_experience=16,
        ai_certifications="CPA",
        ai_summary="VP Finance at a clinical-stage biotech. Manages SEC reporting, investor relations, and capital raise processes. Raised $180M Series C and $220M IPO. Positioned for CFO role at an emerging growth biotech.",
        ai_experience="BDO (2008–2013). Sarepta Therapeutics (2013–2018). Granite Biotech (2018–present).",
        ai_education="MBA, Tuck, 2008; BS Accounting, Penn State, 2005",
        ai_skills=["Biotech CFO", "SEC Reporting", "IPO", "Capital Raises", "Investor Relations", "FDA"],
        notes="Actively looking for CFO role. Target $275K+.",
    ),
    Candidate(
        name="Stephanie Brown", email="sbrown@gmail.com", phone="617-555-0115",
        current_title="Tax Senior", current_company="KPMG",
        location="Boston, MA",
        ai_career_level="mid", ai_years_experience=4,
        ai_certifications="CPA",
        ai_summary="Tax senior at KPMG with strong corporate and partnership tax background. Healthcare and life sciences clients. CPA licensed 2022. Looking to make the move to an in-house tax role at a mid-size or large company.",
        ai_experience="KPMG (2020–present) — tax associate to senior.",
        ai_education="MS Taxation, Bentley, 2020",
        ai_skills=["Corporate Tax", "Partnership Tax", "Healthcare", "ASC 740", "Big 4"],
        notes="Great background for an in-house tax senior. Target $95–110K.",
    ),
    Candidate(
        name="Daniel Murphy", email="dmurphy@gmail.com", phone="617-555-0116",
        current_title="Senior Accountant", current_company="Harbor Financial Group",
        location="Boston, MA",
        ai_career_level="mid", ai_years_experience=5,
        ai_summary="Senior accountant at a mid-size financial services company. Owns the investment accounting and fund reporting. Strong with BlackRock Aladdin and Bloomberg. CFA Level I candidate.",
        ai_experience="State Street (2019–2021). Harbor Financial (2021–present).",
        ai_education="BS Finance, Holy Cross, 2019",
        ai_skills=["Investment Accounting", "Fund Reporting", "Aladdin", "Bloomberg", "Financial Services"],
        notes="Niche skill set. Target $100–115K. Staying in financial services.",
    ),
    Candidate(
        name="Alexandra Davis", email="adavis@gmail.com", phone="617-555-0117",
        current_title="Controller", current_company="Coastal Healthcare Partners",
        location="Boston, MA",
        ai_career_level="senior", ai_years_experience=10,
        ai_certifications="CPA",
        ai_summary="Controller at a multi-site healthcare group managing $150M in revenue across 8 locations. Strong consolidation accounting, cost accounting, and healthcare-specific revenue recognition (ASC 606 + payer contracts). Ready for VP Finance.",
        ai_experience="BDO (2014–2018). Coastal Healthcare (2018–present).",
        ai_education="BS Accounting, UConn, 2014",
        ai_skills=["Healthcare", "Multi-site", "Consolidations", "ASC 606", "Cost Accounting", "Payer Contracts"],
        notes="Strong operator. Target $155–175K. Open to healthcare or adjacent sectors.",
    ),
    Candidate(
        name="Christopher Lee", email="clee@gmail.com", phone="617-555-0118",
        current_title="VP Finance", current_company="TechScale SaaS",
        location="Boston, MA",
        ai_career_level="executive", ai_years_experience=15,
        ai_certifications="CPA",
        ai_summary="VP Finance at a growth-stage SaaS company ($80M ARR). Full P&L ownership, Series C fundraising, and M&A pipeline management. Prior investment banking background at Lazard. Positioned for CFO at $100M–$500M revenue software company.",
        ai_experience="Lazard (2009–2014). Various SaaS CFO/VP roles (2014–present).",
        ai_education="MBA, Columbia, 2009; BA Economics, Yale, 2006",
        ai_skills=["SaaS CFO", "Investment Banking", "M&A", "Series C", "ARR", "SaaS Metrics"],
        notes="High-caliber candidate. Will move for the right CFO role. Target $300K+.",
    ),
    Candidate(
        name="Megan Taylor", email="mtaylor@gmail.com", phone="617-555-0119",
        current_title="Staff Accountant", current_company="Granite State Manufacturing",
        location="Manchester, NH",
        ai_career_level="junior", ai_years_experience=1,
        ai_summary="Entry-level staff accountant at a manufacturing company, one year out of school. Strong work ethic, learning cost accounting and inventory management. Looking to move to Boston for better opportunities. CPA exam studying in progress.",
        ai_experience="Granite State Manufacturing (2024–present).",
        ai_education="BS Accounting, UNH, 2024",
        ai_skills=["Cost Accounting", "Inventory", "Excel", "Manufacturing", "Month-end Close"],
        notes="Early career. Target $62–70K. Willing to relocate to Boston.",
    ),
    Candidate(
        name="Brian Wilson", email="bwilson@gmail.com", phone="617-555-0120",
        current_title="Accounting Manager", current_company="Atlantic Ventures",
        location="Boston, MA",
        ai_career_level="mid", ai_years_experience=8,
        ai_certifications="CPA",
        ai_summary="Accounting Manager at a VC-backed company, managing close, consolidations across 3 entities, and investor reporting. Strong with Netsuite and Carta. Interested in a Controller role with more scope and a growing team.",
        ai_experience="RSM (2016–2020). Atlantic Ventures (2020–present).",
        ai_education="BS Accounting, Babson, 2016",
        ai_skills=["NetSuite", "Carta", "Consolidations", "VC-backed", "Investor Reporting", "CPA"],
        notes="Ready for Controller step. Target $120–135K.",
    ),
    Candidate(
        name="Jessica Moore", email="jmoore@gmail.com", phone="617-555-0121",
        current_title="FP&A Manager", current_company="ClearPath Health",
        location="Boston, MA",
        ai_career_level="senior", ai_years_experience=9,
        ai_summary="FP&A Manager at a healthcare SaaS company, owning the $60M operating budget, long-range plan, and board KPI reporting. Prior consulting background at McKinsey. Strong at translating financial data into operational recommendations.",
        ai_experience="McKinsey & Company (2015–2019). ClearPath Health (2019–present).",
        ai_education="MBA, Dartmouth Tuck, 2015; BS Economics, Williams, 2012",
        ai_skills=["FP&A", "Healthcare", "Board Reporting", "LRP", "McKinsey", "SaaS Metrics"],
        notes="High performer. Target $145–165K. Open to Director FP&A or VP Finance roles.",
    ),
    Candidate(
        name="Andrew Johnson", email="ajohnson@gmail.com", phone="617-555-0122",
        current_title="Director of Finance", current_company="Boston PE Partners",
        location="Boston, MA",
        ai_career_level="executive", ai_years_experience=18,
        ai_certifications="CPA, CFA",
        ai_summary="Director of Finance at a mid-market PE firm managing portfolio finance operations across 8 portfolio companies. Prior investment banking at Goldman Sachs and 10 years in PE finance. Deep deal structuring, leveraged buyout modeling, and portfolio monitoring expertise.",
        ai_experience="Goldman Sachs (2006–2011). Boston PE Partners (2011–present).",
        ai_education="MBA, Kellogg, 2006; BS Finance, Notre Dame, 2003",
        ai_skills=["Private Equity", "LBO Modeling", "Portfolio Finance", "Deal Structuring", "Goldman Sachs"],
        notes="Looking at operating CFO or portfolio company CFO roles. Target $300K+.",
    ),
]

for c in candidates:
    db.add(c)
db.commit()
print(f"  ✓ {len(candidates)} candidates")


# ── Employer Profiles (12) ─────────────────────────────────────────────────
print("Seeding employer profiles...")

employers = [
    EmployerProfile(
        company_name="Acme Manufacturing Corp",
        website_url="https://acmemfg.com",
        primary_contact_email="cfo@acmemfg.com",
        phone="617-555-1001",
        ai_industry="Manufacturing",
        ai_company_size="200 employees, $120M revenue",
        ai_company_overview="PE-backed precision manufacturer in Waltham, MA. Summit Partners invested in 2021. Producing specialty parts for aerospace and defense. Tight close cadence, PE sponsor reporting every month.",
        ai_hiring_needs='["Controller — CPA required, manufacturing cost accounting, NetSuite"]',
        ai_talking_points='["PE sponsor reporting", "Urgent timeline — current Controller leaving end of month", "Strong culture, lean team", "Salary flexible to $155K"]',
        ai_red_flags="High pressure close environment. PE reporting expectations are demanding.",
        relationship_status="Active",
    ),
    EmployerProfile(
        company_name="BioNovate Therapeutics",
        website_url="https://bionovate.com",
        primary_contact_email="cfo@bionovate.com",
        phone="617-555-1002",
        ai_industry="Biotechnology",
        ai_company_size="350 employees, clinical-stage",
        ai_company_overview="Cambridge-based clinical-stage biotech with 2 compounds in Phase 3. Recently raised $180M Series C. SEC-reporting company. Building out the finance team ahead of potential FDA approval in 2026.",
        ai_hiring_needs='["VP Finance — IPO experience required", "Senior Accounting Manager — biotech background preferred"]',
        ai_talking_points='["Pre-approval stage — exciting milestone ahead", "Equity compensation is meaningful", "World-class science team", "Recently raised $180M"]',
        ai_red_flags="Clinical-stage means no revenue. Finance team is building fast — some management immaturity.",
        relationship_status="Active",
    ),
    EmployerProfile(
        company_name="TechScale SaaS Inc",
        website_url="https://techscale.io",
        primary_contact_email="hr@techscale.io",
        phone="617-555-1003",
        ai_industry="Software / SaaS",
        ai_company_size="180 employees, $80M ARR",
        ai_company_overview="Boston-based B2B SaaS company serving mid-market HR teams. Series C company growing 40% YoY. Strong product-market fit. Finance team of 8 currently — expanding.",
        ai_hiring_needs='["CFO — series C stage, M&A experience preferred", "FP&A Manager — SaaS metrics expertise"]',
        ai_talking_points='["40% YoY growth", "Clear path to Series D or strategic sale in 3 years", "Equity is meaningful", "Strong product team"]',
        ai_red_flags="Founders are very involved in finance decisions. CFO will need strong executive presence.",
        relationship_status="Active",
    ),
    EmployerProfile(
        company_name="ClearPath Health Systems",
        website_url="https://clearpathhealth.com",
        primary_contact_email="talent@clearpathhealth.com",
        phone="617-555-1004",
        ai_industry="Healthcare Technology",
        ai_company_size="400 employees, $95M revenue",
        ai_company_overview="Boston-based healthcare SaaS platform serving hospital systems. Profitable, growing 25% YoY. Finance team is 12 people. Strong culture and very low turnover.",
        ai_hiring_needs='["Accounting Manager", "Senior FP&A Analyst"]',
        ai_talking_points='["Profitable — rare in healthtech", "Excellent benefits and PTO", "Mission-driven culture", "Flexible hybrid"]',
        ai_red_flags=None,
        relationship_status="Active",
    ),
    EmployerProfile(
        company_name="Atlantic Distribution Co",
        website_url="https://atlanticdist.com",
        primary_contact_email="michael@atlanticdist.com",
        phone="617-555-1005",
        ai_industry="Distribution / Logistics",
        ai_company_size="500 employees, $300M revenue",
        ai_company_overview="Family-owned distribution company based in Boston, in business for 50 years. Third-generation ownership. Strong culture, low turnover, and a very stable business. Currently going through a generational transition — bringing in professional management.",
        ai_hiring_needs='["CFO — first professional CFO, replace founder-CFO", "Controller"]',
        ai_talking_points='["First professional CFO — greenfield opportunity to build systems", "Profitable and debt-free", "Strong family culture", "Competitive salary + profit sharing"]',
        ai_red_flags="Founder still involved as Chairman. Must be comfortable with family business dynamics.",
        relationship_status="Active",
    ),
    EmployerProfile(
        company_name="Summit CPA Group",
        website_url="https://summitcpa.com",
        primary_contact_email="partners@summitcpa.com",
        phone="617-555-1006",
        ai_industry="Public Accounting",
        ai_company_size="55 employees",
        ai_company_overview="Regional CPA firm in Boston serving closely-held businesses and high-net-worth individuals. Tax, audit, and advisory services. Growing 15% annually. Partner track available.",
        ai_hiring_needs='["Tax Manager — partner track in 4 years", "Audit Senior"]',
        ai_talking_points='["Partner track available in 3–4 years", "Flexible schedule post-busy season", "Strong mentorship culture", "Diverse client base"]',
        ai_red_flags=None,
        relationship_status="Active",
    ),
    EmployerProfile(
        company_name="Harbor Financial Group",
        website_url="https://harborfinancial.com",
        primary_contact_email="hr@harborfinancial.com",
        phone="617-555-1007",
        ai_industry="Asset Management",
        ai_company_size="120 employees, $8B AUM",
        ai_company_overview="Boston-based registered investment advisor managing $8B in assets for institutional clients. Long-only equity and fixed income strategies. Finance team of 6. Very stable business, consistent fee income.",
        ai_hiring_needs='["Senior Fund Accountant", "VP Finance / Controller"]',
        ai_talking_points='["Stable fee-based business", "Strong bonus potential tied to AUM growth", "Collaborative environment", "Excellent benefits"]',
        ai_red_flags=None,
        relationship_status="Active",
    ),
    EmployerProfile(
        company_name="Coastal Healthcare Partners",
        website_url="https://coastalhealthcare.com",
        primary_contact_email="cfo@coastalhealthcare.com",
        phone="617-555-1008",
        ai_industry="Healthcare",
        ai_company_size="800 employees, $150M revenue",
        ai_company_overview="Multi-site healthcare group operating 8 outpatient facilities across New England. Growing through acquisition. Currently integrating 2 new facilities. Complex payer mix and multi-entity consolidations.",
        ai_hiring_needs='["VP Finance — multi-site healthcare experience essential", "Revenue Cycle Manager"]',
        ai_talking_points='["Acquisition growth story", "Impact on patients and communities", "Strong benefits", "Boston HQ with travel to sites"]',
        ai_red_flags="Integration work is heavy right now. New VP Finance will walk into a busy consolidation project.",
        relationship_status="Active",
    ),
    EmployerProfile(
        company_name="Granite State Manufacturing",
        website_url="https://granitestatmfg.com",
        primary_contact_email="president@granitestatmfg.com",
        phone="603-555-1009",
        ai_industry="Manufacturing",
        ai_company_size="90 employees, $45M revenue",
        ai_company_overview="Family-owned precision machining company in Manchester, NH. Profitable, debt-free, and growing. First time using a recruiter. Looking for their first Controller to replace the owner's wife who has been managing the books.",
        ai_hiring_needs='["Controller — first hire, building processes from scratch"]',
        ai_talking_points='["True greenfield — build systems from scratch", "Ownership mentality wanted", "Competitive comp for NH market", "Low turnover culture"]',
        ai_red_flags="Books are informal. Will require a patient Controller comfortable with cleanup work.",
        relationship_status="Prospect",
    ),
    EmployerProfile(
        company_name="Boston PE Partners",
        website_url="https://bostonpepartners.com",
        primary_contact_email="mds@bostonpepartners.com",
        phone="617-555-1010",
        ai_industry="Private Equity",
        ai_company_size="30 employees, $2B AUM",
        ai_company_overview="Mid-market private equity firm focused on lower middle market industrials and business services. 8 portfolio companies. Sophisticated finance team. Looking to add a VP of Portfolio Finance to oversee reporting across all portfolio companies.",
        ai_hiring_needs='["VP Portfolio Finance", "Senior Associate — Finance"]',
        ai_talking_points='["Excellent carry and bonus structure", "Work across 8 unique businesses", "Direct exposure to GPs and deal team", "Boston office, limited travel"]',
        ai_red_flags=None,
        relationship_status="Active",
    ),
    EmployerProfile(
        company_name="Vertex Growth Capital",
        website_url="https://vertexgrowth.com",
        primary_contact_email="cfo@vertexgrowth.com",
        phone="617-555-1011",
        ai_industry="Venture Capital / Growth Equity",
        ai_company_size="25 employees",
        ai_company_overview="Boston-based growth equity fund focused on Series B and C software companies. $800M fund. Fund accounting, LP reporting, and tax compliance. Very lean finance team — need a strong Controller.",
        ai_hiring_needs='["Fund Controller — fund accounting, ASC 820, LP reporting"]',
        ai_talking_points='["Top-tier firm brand name", "Exposure to exciting growth companies", "Strong comp and carry", "Small collaborative team"]',
        ai_red_flags="Very lean team. Controller will wear many hats.",
        relationship_status="Active",
    ),
    EmployerProfile(
        company_name="Fieldstone Capital Management",
        website_url="https://fieldstonecap.com",
        primary_contact_email="ops@fieldstonecap.com",
        phone="617-555-1012",
        ai_industry="Hedge Fund",
        ai_company_size="40 employees, $1.2B AUM",
        ai_company_overview="Boston-based long/short equity hedge fund. Strong performance track record. Finance function is 3 people — CFO, Controller, and one senior analyst. Looking to add a Controller as current Controller is being promoted.",
        ai_hiring_needs='["Controller — hedge fund accounting, PnL attribution, investor allocations"]',
        ai_talking_points='["Strong performance bonus tied to fund returns", "Collaborative 3-person team", "Excellent systems — Geneva, Bloomberg, Advent", "Direct CFO mentorship"]',
        ai_red_flags=None,
        relationship_status="Active",
    ),
]

for e in employers:
    db.add(e)
db.commit()

# Fetch inserted employers to get IDs
all_employers = db.query(EmployerProfile).order_by(EmployerProfile.id.desc()).limit(12).all()
all_employers.reverse()
emp = {e.company_name: e.id for e in all_employers}
print(f"  ✓ {len(employers)} employers")


# ── Job Orders (18) ────────────────────────────────────────────────────────
print("Seeding job orders...")

job_orders = [
    JobOrder(employer_profile_id=emp.get("Acme Manufacturing Corp"),
        title="Controller", location="Waltham, MA", salary_min=135000, salary_max=155000, status="open",
        requirements="CPA required. 8+ years experience. Manufacturing cost accounting and NetSuite. PE-backed environment experience strongly preferred. Tight close timeline — must be comfortable with month-end crunch."),
    JobOrder(employer_profile_id=emp.get("BioNovate Therapeutics"),
        title="VP Finance", location="Cambridge, MA", salary_min=200000, salary_max=240000, status="open",
        requirements="CPA preferred. 12+ years including biotech. IPO or SEC reporting experience required. Will lead finance team of 10 and manage external auditors. Board presentation experience essential."),
    JobOrder(employer_profile_id=emp.get("BioNovate Therapeutics"),
        title="Senior Accounting Manager", location="Cambridge, MA", salary_min=130000, salary_max=150000, status="open",
        requirements="CPA required. 7+ years including 2+ in biotech. Clinical trial accounting experience a plus. NetSuite or Workday. Will own the close, manage 3 staff accountants."),
    JobOrder(employer_profile_id=emp.get("TechScale SaaS Inc"),
        title="CFO", location="Boston, MA", salary_min=280000, salary_max=340000, status="open",
        requirements="CPA preferred or MBA. 15+ years with at least 5 as CFO or VP Finance at a SaaS company. Series C+ fundraising experience. M&A transaction experience. Must have operated at $50M+ ARR."),
    JobOrder(employer_profile_id=emp.get("TechScale SaaS Inc"),
        title="FP&A Manager", location="Boston, MA", salary_min=120000, salary_max=140000, status="open",
        requirements="5+ years FP&A. SaaS company experience essential. ARR, CAC, LTV, NRR modeling. Adaptive Insights or Anaplan experience. Will own the annual plan and monthly board KPI package."),
    JobOrder(employer_profile_id=emp.get("ClearPath Health Systems"),
        title="Accounting Manager", location="Boston, MA", salary_min=105000, salary_max=120000, status="open",
        requirements="CPA preferred. 5+ years including 1+ as manager. Healthcare or SaaS background. NetSuite or Sage Intacct. Manage a team of 3. Own the monthly close."),
    JobOrder(employer_profile_id=emp.get("ClearPath Health Systems"),
        title="Senior FP&A Analyst", location="Boston, MA", salary_min=85000, salary_max=100000, status="open",
        requirements="3–6 years FP&A experience. Healthcare or SaaS preferred. Strong Excel and PowerPoint. Will support the FP&A Manager on budgeting, forecasting, and board materials."),
    JobOrder(employer_profile_id=emp.get("Atlantic Distribution Co"),
        title="CFO", location="Boston, MA", salary_min=250000, salary_max=300000, status="open",
        requirements="CPA required. 15+ years with CFO or VP Finance experience. Distribution, manufacturing, or family-owned business background. Will be the first professional CFO — strong systems and process mindset. ERP implementation experience a plus."),
    JobOrder(employer_profile_id=emp.get("Atlantic Distribution Co"),
        title="Controller", location="Boston, MA", salary_min=140000, salary_max=160000, status="open",
        requirements="CPA required. 8+ years. Distribution or manufacturing background. NetSuite or Epicor experience. Will build out the accounting team under new CFO."),
    JobOrder(employer_profile_id=emp.get("Summit CPA Group"),
        title="Tax Manager", location="Boston, MA", salary_min=110000, salary_max=135000, status="open",
        requirements="CPA required. 7+ years tax experience, public accounting background preferred. Corporate and pass-through tax. Partner track opportunity in 3–4 years."),
    JobOrder(employer_profile_id=emp.get("Harbor Financial Group"),
        title="Senior Fund Accountant", location="Boston, MA", salary_min=90000, salary_max=110000, status="open",
        requirements="3–6 years fund accounting experience. Mutual fund or separately managed account background. Advent Geneva or similar system. Strong reconciliation and NAV calculation skills."),
    JobOrder(employer_profile_id=emp.get("Coastal Healthcare Partners"),
        title="VP Finance", location="Boston, MA", salary_min=175000, salary_max=210000, status="open",
        requirements="CPA required. 12+ years including multi-site healthcare. Payer contract accounting, ASC 606, and consolidations across multiple entities. M&A integration experience a plus. Will oversee Controller and revenue cycle teams."),
    JobOrder(employer_profile_id=emp.get("Granite State Manufacturing"),
        title="Controller", location="Manchester, NH", salary_min=110000, salary_max=130000, status="open",
        requirements="CPA preferred. 6+ years including some manufacturing. Comfortable building processes from scratch — current accounting is informal. NetSuite or SAP implementation experience a plus. First Controller hire for this company."),
    JobOrder(employer_profile_id=emp.get("Boston PE Partners"),
        title="VP Portfolio Finance", location="Boston, MA", salary_min=200000, salary_max=240000, status="open",
        requirements="CPA required. 10+ years with PE or portfolio company CFO experience. Will oversee financial reporting across 8 portfolio companies, coordinate with deal team, and manage quarterly LP reporting."),
    JobOrder(employer_profile_id=emp.get("Vertex Growth Capital"),
        title="Fund Controller", location="Boston, MA", salary_min=150000, salary_max=175000, status="open",
        requirements="CPA required. 7+ years with fund accounting experience. VC or growth equity fund required. ASC 820 fair value, LP reporting, K-1 prep. Allvue or iLevel a plus."),
    JobOrder(employer_profile_id=emp.get("Fieldstone Capital Management"),
        title="Controller", location="Boston, MA", salary_min=160000, salary_max=190000, status="open",
        requirements="5+ years hedge fund accounting. P&L attribution, investor allocations, and NAV. Geneva or Advent required. Bloomberg experience helpful. Will report directly to CFO."),
    JobOrder(employer_profile_id=emp.get("BioNovate Therapeutics"),
        title="Director of Tax", location="Cambridge, MA", salary_min=170000, salary_max=200000, status="open",
        requirements="CPA required. 12+ years with mix of Big 4 and in-house biotech tax. ASC 740, R&D credits, equity compensation tax. Will build the in-house tax function from scratch."),
    JobOrder(employer_profile_id=emp.get("TechScale SaaS Inc"),
        title="Controller", location="Boston, MA", salary_min=155000, salary_max=180000, status="filled",
        requirements="CPA required. 8+ years including SaaS. Revenue recognition (ASC 606), equity compensation accounting, and multi-currency consolidations. Will manage team of 5.",
        filled_at=dt(45)),
]

for j in job_orders:
    db.add(j)
db.commit()
print(f"  ✓ {len(job_orders)} job orders")


# ── Bookings (30) ──────────────────────────────────────────────────────────
print("Seeding bookings...")

bookings = [
    # Today
    Booking(booking_type="outbound_employer", employer_name="Michael Torres", employer_email="mtorres@acmemfg.com",
        company_name="Acme Manufacturing Corp", date=today, time_slot="9:00 AM", status="confirmed",
        meeting_url="https://zoom.us/j/111111111",
        meeting_summary="Met with CFO Michael Torres re: Controller search. Company is 200 employees, PE-backed by Summit Partners since 2021. Need a CPA with manufacturing cost accounting and NetSuite. Current Controller leaving end of month — urgent timeline. Salary flexible to $155K. Strong fit matters — lean team. Follow up Friday with top 3 candidates.",
        meeting_next_steps="• Send top 3 candidates by Friday\n• Confirm salary range in writing\n• Schedule second round for top candidate next week",
        call_outcome="placed", call_notes="High urgency. Budget approved. Decision maker is in the room.",
        created_at=dt(0, 8)),
    Booking(booking_type="outbound_candidate", employer_name="Sarah Chen", employer_email="schen@gmail.com",
        date=today, time_slot="11:30 AM", status="confirmed",
        meeting_url="https://zoom.us/j/222222222",
        meeting_summary="Intro call with Sarah Chen. Currently Senior Accountant at MedBridge Health in Boston. 5 years, strong NetSuite, healthcare background. Interested in Accounting Manager or Controller track. Target $95–110K. Hybrid preferred. Very polished communicator — would present well to clients.",
        meeting_next_steps="• Send ClearPath Health Accounting Manager JD\n• Follow up Wednesday to confirm interest\n• Prep her for employer interview style",
        call_outcome="follow_up", call_notes="Strong candidate. Matches ClearPath and potentially Acme Mfg.",
        created_at=dt(0, 9)),

    # Yesterday
    Booking(booking_type="outbound_employer", employer_name="Jennifer Walsh CFO", employer_email="cfo@bionovate.com",
        company_name="BioNovate Therapeutics", date=d(1), time_slot="2:00 PM", status="confirmed",
        meeting_url="https://zoom.us/j/333333333",
        meeting_summary="Call with BioNovate CFO to discuss VP Finance search. Clinical-stage biotech, 350 people, recently raised $180M Series C. Need someone with IPO experience who can lead the finance team of 10. Board presentation experience essential. Salary to $240K + equity. Timeline is 60 days.",
        meeting_next_steps="• Identify 5 VP Finance candidates with IPO experience\n• Send search update by end of week\n• Schedule next check-in for 2 weeks",
        call_outcome="placed", call_notes="Well-organized client. Clear requirements. Strong equity package.",
        created_at=dt(1, 13)),

    # 3 days ago
    Booking(booking_type="outbound_candidate", employer_name="David Kim", employer_email="dkim@gmail.com",
        date=d(3), time_slot="10:00 AM", status="confirmed",
        meeting_url="https://zoom.us/j/444444444",
        meeting_summary="Intro call with David Kim, FP&A Manager at CloudMetrics. Strong SaaS background — owns annual budget for a $45M ARR company. Expert in SaaS metrics. Target $125–145K. Adaptive Insights certified. Great fit for TechScale FP&A Manager role.",
        meeting_next_steps="• Submit David to TechScale FP&A Manager role\n• Schedule interview prep call before employer interview",
        call_outcome="follow_up", call_notes="Top candidate for TechScale. Move quickly.",
        created_at=dt(3, 9)),

    Booking(booking_type="inbound", employer_name="Robert Huang", employer_email="rhuang@gmail.com",
        company_name="Atlantic Distribution Co", date=d(3), time_slot="3:00 PM", status="confirmed",
        meeting_url="https://zoom.us/j/555555555",
        meeting_summary="Inbound booking from Atlantic Distribution. Robert Huang is the interim CFO looking for a permanent hire. Family-owned distribution company, $300M revenue, debt-free. Need a CFO who can be their first professional one. Current finance team is informal. Budget is $250–300K.",
        meeting_next_steps="• Develop CFO target list — family business specialists\n• Send Robert candidate profiles by end of week",
        call_outcome="placed", call_notes="Strong engagement. Long-term relationship opportunity.",
        created_at=dt(3, 14)),

    # 1 week ago
    Booking(booking_type="outbound_candidate", employer_name="Jennifer Walsh", employer_email="jwalsh@gmail.com",
        date=d(7), time_slot="9:00 AM", status="confirmed",
        meeting_url="https://zoom.us/j/666666666",
        meeting_summary="Intro call with Jennifer Walsh, Audit Manager at Deloitte. 9 years Big 4, life sciences clients. Strong technical accounting. Ready to move to industry — Director of Finance or VP role. Target $130–150K. Downtown Boston preferred. Excellent presentation skills.",
        meeting_next_steps="• Match to BioNovate Senior Accounting Manager role\n• Also explore Coastal Healthcare VP Finance",
        call_outcome="follow_up",
        created_at=dt(7, 8)),

    Booking(booking_type="outbound_employer", employer_name="Karen Simmons", employer_email="partners@summitcpa.com",
        company_name="Summit CPA Group", date=d(7), time_slot="1:00 PM", status="confirmed",
        meeting_url="https://zoom.us/j/777777777",
        meeting_summary="Call with Summit CPA Group managing partner. Looking for a Tax Manager — partner track in 3–4 years. Salary $110–135K. Strong firm culture. 55 employees, growing 15% per year. Need CPA with 7+ years and corporate/pass-through tax.",
        meeting_next_steps="• Send James O'Brien and Stephanie Brown profiles\n• Both have strong public accounting tax backgrounds",
        call_outcome="placed",
        created_at=dt(7, 12)),

    # 2 weeks ago
    Booking(booking_type="outbound_candidate", employer_name="Amanda Foster", employer_email="afoster@gmail.com",
        date=d(14), time_slot="10:00 AM", status="confirmed",
        meeting_url="https://zoom.us/j/888888888",
        meeting_summary="Intro call with Amanda Foster, Accounting Manager at Harbor Logistics. KPMG background, CPA, 6 years experience. Wants to step up to Controller. Target $110–125K. South Shore preferred but open to Boston with hybrid. ASC 842 experience is a real differentiator.",
        meeting_next_steps="• Match to Granite State Controller role (NH, remote-friendly)\n• Also check ClearPath Accounting Manager",
        call_outcome="follow_up",
        created_at=dt(14, 9)),

    Booking(booking_type="outbound_employer", employer_name="Thomas Wei", employer_email="hr@techscale.io",
        company_name="TechScale SaaS Inc", date=d(14), time_slot="2:00 PM", status="confirmed",
        meeting_url="https://zoom.us/j/999999999",
        meeting_summary="Second call with TechScale to update on CFO search and add a Controller role. CFO search is progressing — have 3 candidates in process. They also need a Controller for the finance team (just promoted last one to VP). Budget $155–180K. CPA required, SaaS preferred.",
        meeting_next_steps="• Continue CFO search — send 2 more profiles\n• Begin Controller search immediately",
        call_outcome="placed",
        created_at=dt(14, 13)),

    # 3 weeks ago
    Booking(booking_type="inbound_candidate", employer_name="Marcus Rivera", employer_email="mrivera@gmail.com",
        date=d(21), time_slot="11:00 AM", status="confirmed",
        meeting_url="https://zoom.us/j/101010101",
        meeting_summary="Inbound call from Marcus Rivera at Deloitte. Big 4 senior, financial services clients. 4 years, CPA. Very polished. Strong SOX background. Target $90–105K. Ready to make the move to industry now. Good fit for Harbor Financial or a financial services company.",
        meeting_next_steps="• Submit to Harbor Financial Senior Fund Accountant role\n• He has the right background and is motivated",
        call_outcome="follow_up",
        created_at=dt(21, 10)),

    Booking(booking_type="outbound_employer", employer_name="Patricia Kelley", employer_email="cfo@coastalhealthcare.com",
        company_name="Coastal Healthcare Partners", date=d(21), time_slot="3:30 PM", status="confirmed",
        meeting_url="https://zoom.us/j/202020202",
        meeting_summary="Call with Coastal Healthcare CFO. Looking for VP Finance — multi-site healthcare, integration experience. Currently integrating 2 new acquisitions. $150M revenue, 8 sites. Need a strong operator who can handle complexity. Budget $175–210K. Timeline is 45 days.",
        meeting_next_steps="• Alexandra Davis is the strongest fit — multi-site healthcare Controller\n• Send her profile immediately",
        call_outcome="placed",
        created_at=dt(21, 15)),

    # 1 month ago
    Booking(booking_type="outbound_candidate", employer_name="Rachel Green", employer_email="rgreen@gmail.com",
        date=d(30), time_slot="9:00 AM", status="confirmed",
        meeting_url="https://zoom.us/j/303030303",
        meeting_summary="Call with Rachel Green, Controller at Bloom Retail. PE-backed, $90M revenue, team of 6. 11 years experience, CPA. Strong retail accounting — inventory, consolidations, PE sponsor reporting. Target $165–185K. Ready for VP Finance or divisional CFO. Strong candidate.",
        meeting_next_steps="• Match to Coastal Healthcare VP Finance\n• Also flag for Atlantic Distribution CFO (step up)",
        call_outcome="follow_up",
        created_at=dt(30, 8)),

    Booking(booking_type="outbound_employer", employer_name="Sam Okafor", employer_email="mds@bostonpepartners.com",
        company_name="Boston PE Partners", date=d(30), time_slot="1:00 PM", status="confirmed",
        meeting_url="https://zoom.us/j/404040404",
        meeting_summary="First call with Boston PE Partners managing director. Looking for VP Portfolio Finance to oversee 8 portfolio companies. High-caliber firm, $2B AUM. Need someone who has been a portfolio company CFO or VP Finance in PE. Carry and bonus are meaningful. Budget $200–240K.",
        meeting_next_steps="• Andrew Johnson is perfect for this\n• Also consider Robert Huang if he wants PE side",
        call_outcome="placed",
        created_at=dt(30, 12)),

    # 6 weeks ago
    Booking(booking_type="outbound_candidate", employer_name="Kevin Park", employer_email="kpark@gmail.com",
        date=d(42), time_slot="10:00 AM", status="confirmed",
        meeting_url="https://zoom.us/j/505050505",
        meeting_summary="Call with Kevin Park, VP Finance at Granite Biotech. Led $220M IPO. 16 years, CPA. Looking for CFO role at emerging growth biotech. Target $275K+. Exceptional candidate — the equity raise experience is rare. Match to BioNovate VP Finance or any pre-IPO biotech CFO.",
        meeting_next_steps="• Submit to BioNovate VP Finance immediately — top priority\n• Also reach out to 2 other biotech clients",
        call_outcome="follow_up",
        created_at=dt(42, 9)),

    # 2 months ago
    Booking(booking_type="outbound_employer", employer_name="Alex Fitzgerald", employer_email="cfo@vertexgrowth.com",
        company_name="Vertex Growth Capital", date=d(60), time_slot="11:00 AM", status="confirmed",
        meeting_url="https://zoom.us/j/606060606",
        meeting_summary="First call with Vertex Growth Capital. Looking for Fund Controller — VC/growth equity fund accounting, ASC 820, LP reporting. Small team, high-quality work. Budget $150–175K. CPA required. Allvue or iLevel a plus. Need someone in 60 days.",
        meeting_next_steps="• Identify 3 fund accounting candidates — VC/PE specific\n• This is a niche search",
        call_outcome="placed",
        created_at=dt(60, 10)),

    Booking(booking_type="outbound_candidate", employer_name="Christopher Lee", employer_email="clee@gmail.com",
        date=d(60), time_slot="2:00 PM", status="confirmed",
        meeting_url="https://zoom.us/j/707070707",
        meeting_summary="Call with Christopher Lee, VP Finance at TechScale. Lazard background, now SaaS CFO. 15 years, CPA. Looking for CFO role. Target $300K+. Very strong candidate — investment banking + operating SaaS experience is rare. Top target for TechScale CFO or any Series C+ SaaS company.",
        meeting_next_steps="• Present to TechScale board as CFO candidate\n• Also keep in pipeline for 2 other SaaS clients",
        call_outcome="follow_up",
        created_at=dt(60, 13)),

    # Cancelled / no-show examples
    Booking(booking_type="outbound_employer", employer_name="Tom Bradley", employer_email="tbradley@randco.com",
        company_name="Rand Co", date=d(5), time_slot="10:00 AM", status="cancelled",
        notes="Client cancelled search — decided to promote internally.", call_outcome="not_a_fit",
        created_at=dt(10, 10)),
    Booking(booking_type="outbound_candidate", employer_name="Peter Walsh", employer_email="pwalsh@gmail.com",
        date=d(10), time_slot="3:00 PM", status="confirmed",
        call_outcome="no_show", notes="No show — did not respond to follow-up emails.",
        created_at=dt(12, 14)),

    # Upcoming confirmed
    Booking(booking_type="outbound_employer", employer_name="Nicole Chen CFO", employer_email="cfo@fieldstone.com",
        company_name="Fieldstone Capital Management", date=today + timedelta(days=1), time_slot="10:00 AM", status="confirmed",
        meeting_url="https://zoom.us/j/808080808",
        notes="First call. Hedge fund Controller search. Need fund accounting background — Geneva. Budget $160–190K.",
        created_at=dt(2, 16)),
    Booking(booking_type="outbound_candidate", employer_name="James O'Brien", employer_email="jobrien@gmail.com",
        date=today + timedelta(days=2), time_slot="9:00 AM", status="confirmed",
        meeting_url="https://zoom.us/j/909090909",
        notes="Intro call with James OBrien. Tax Manager at PwC. CPA, 10 years. Looking at in-house Director Tax or Tax Manager roles. Prep — Summit CPA and BioNovate Director Tax are both good fits.",
        created_at=dt(1, 11)),
    Booking(booking_type="outbound_employer", employer_name="Bill Grayson", employer_email="president@granitestatmfg.com",
        company_name="Granite State Manufacturing", date=today + timedelta(days=3), time_slot="1:00 PM", status="confirmed",
        meeting_url="https://zoom.us/j/121212121",
        notes="Follow-up call with Granite State. Update on Controller search. Have 2 candidates ready. Manage expectations on timeline — this is a niche NH-based role.",
        created_at=dt(1, 15)),

    # Pending (not yet confirmed)
    Booking(booking_type="inbound", employer_name="Sarah Thompson", employer_email="sthompson@newco.com",
        company_name="NewCo Inc", date=today + timedelta(days=5), time_slot="2:00 PM", status="pending",
        notes="New inbound from tech company. Wants to discuss CFO search.",
        created_at=dt(0, 10)),
    Booking(booking_type="inbound_candidate", employer_name="Alex Reyes", employer_email="areyes@gmail.com",
        date=today + timedelta(days=4), time_slot="10:00 AM", status="pending",
        notes="Inbound candidate. Controller background. 10 years. Referred by Jennifer Walsh.",
        created_at=dt(0, 11)),

    # Historical — completed well-documented calls
    Booking(booking_type="outbound_candidate", employer_name="Emily Rodriguez", employer_email="erodriguez@gmail.com",
        date=d(45), time_slot="10:00 AM", status="confirmed",
        meeting_url="https://zoom.us/j/131313131",
        meeting_summary="Call with Emily Rodriguez, Director of Finance at Vertex Pharma. 14 years, CPA, MBA from HBS. Biotech specialist — clinical trial accounting, ASC 805. Exploring VP Finance or CFO. Target $200K+. Exceptional background. Not actively looking but worth staying close to.",
        meeting_next_steps="• Stay in touch — reach out again in 3 months or if ideal role comes up\n• Flag for BioNovate VP Finance if they open the role",
        call_outcome="follow_up",
        created_at=dt(45, 9)),
    Booking(booking_type="outbound_employer", employer_name="Howard Kim", employer_email="hr@harborfinancial.com",
        company_name="Harbor Financial Group", date=d(45), time_slot="3:00 PM", status="confirmed",
        meeting_url="https://zoom.us/j/141414141",
        meeting_summary="Call with Harbor Financial HR director. Looking for Senior Fund Accountant and Controller. AUM is $8B, very stable business. Geneva-based system. Competitive bonus. Need people with investment accounting background — mutual fund or SMA experience. Budget $90–110K for senior, $165–190K for Controller.",
        meeting_next_steps="• Marcus Rivera for Senior Fund Accountant — exact background match\n• Daniel Murphy also worth presenting for the senior role",
        call_outcome="placed",
        created_at=dt(45, 14)),
    Booking(booking_type="outbound_candidate", employer_name="Nicole Williams", employer_email="nwilliams@gmail.com",
        date=d(50), time_slot="11:00 AM", status="confirmed",
        meeting_url="https://zoom.us/j/151515151",
        meeting_summary="Intro call with Nicole Williams, Accounting Manager at Summit CPA Group. 7 years public accounting, CPA. Wants to move to private industry for work-life balance. Broad skillset — tax, audit, advisory for small businesses. Target $100–115K. Great fit for a mid-size company Accounting Manager role.",
        meeting_next_steps="• Match to ClearPath Health Accounting Manager — strong fit on culture and comp",
        call_outcome="follow_up",
        created_at=dt(50, 10)),
    Booking(booking_type="outbound_employer", employer_name="David Park", employer_email="ops@fieldstonecap.com",
        company_name="Fieldstone Capital Management", date=d(55), time_slot="2:00 PM", status="confirmed",
        meeting_url="https://zoom.us/j/161616161",
        meeting_summary="First call with Fieldstone Capital. Hedge fund Controller search — existing Controller being promoted to VP. Need fund accounting (P&L attribution, investor allocations, NAV), Geneva system. 3-person finance team, CFO is excellent mentor. Budget $160–190K plus strong performance bonus. 5-year horizon is very stable.",
        meeting_next_steps="• This is a specialized search — start with hedge fund-specific candidates\n• Daniel Murphy has SMA background — worth a look",
        call_outcome="placed",
        created_at=dt(55, 13)),
    Booking(booking_type="outbound_candidate", employer_name="Andrew Johnson", employer_email="ajohnson@gmail.com",
        date=d(55), time_slot="4:00 PM", status="confirmed",
        meeting_url="https://zoom.us/j/171717171",
        meeting_summary="Call with Andrew Johnson, Director of Finance at Boston PE Partners. Goldman background, 18 years in PE and deal finance. CPA + CFA. Exploring operating CFO or portfolio company CFO role. Target $300K+. Exceptional candidate — PE and deal experience is rare in a CFO search. Move quickly on the right opportunity.",
        meeting_next_steps="• Present to Boston PE Partners VP Portfolio Finance role — he would be excellent\n• Keep in pipeline for any CFO searches at PE-backed companies",
        call_outcome="follow_up",
        created_at=dt(55, 15)),
]

for b in bookings:
    db.add(b)
db.commit()
print(f"  ✓ {len(bookings)} bookings")



print("\n✅ Seed complete.")
print("   Run 'python run_backfill.py' next to generate embeddings for all new records.")
