"""add hourly rate range and employment type to job orders

Revision ID: 039ab00599f3
Revises: ad0e898204e5
Create Date: 2026-07-23 08:22:26.814230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039ab00599f3'
down_revision: Union[str, None] = 'ad0e898204e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_orders', sa.Column('hourly_min', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('job_orders', sa.Column('hourly_max', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('job_orders', sa.Column('employment_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_orders', 'employment_type')
    op.drop_column('job_orders', 'hourly_max')
    op.drop_column('job_orders', 'hourly_min')
    # ### end Alembic commands ###
