"""add sms_consent to bookings

Revision ID: 061c54194432
Revises: 47aab21e436b
Create Date: 2026-06-25 09:22:35.842738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061c54194432'
down_revision: Union[str, None] = '47aab21e436b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('sms_consent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('bookings', sa.Column('sms_consent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'sms_consent_at')
    op.drop_column('bookings', 'sms_consent')
    # ### end Alembic commands ###
