"""ep16_add_tenant_id_to_bookings_backfill_nulls

Revision ID: 11ae0fa76851
Revises: 46a2f9a418dc
Create Date: 2026-03-31 02:32:11.115818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11ae0fa76851"
down_revision: Union[str, None] = "46a2f9a418dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- schema change (autogenerated will put this here) ---
    op.add_column("bookings", sa.Column("tenant_id", sa.String(100), nullable=True))
    op.create_index("ix_bookings_tenant_id", "bookings", ["tenant_id"])

    # --- data backfill (add this manually) ---
    op.execute("UPDATE bookings SET tenant_id = 'ryze' WHERE tenant_id IS NULL")
    op.execute("UPDATE candidates SET tenant_id = 'ryze' WHERE tenant_id IS NULL")
    op.execute(
        "UPDATE employer_profiles SET tenant_id = 'ryze' WHERE tenant_id IS NULL"
    )
    op.execute("UPDATE job_orders SET tenant_id = 'ryze' WHERE tenant_id IS NULL")
    op.execute("UPDATE users SET tenant_id = 'ryze' WHERE tenant_id IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("candidate_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "bookings_candidate_id_fkey", "bookings", "candidates", ["candidate_id"], ["id"]
    )
    op.drop_index(op.f("ix_bookings_tenant_id"), table_name="bookings")
    op.drop_column("bookings", "tenant_id")
    # ### end Alembic commands ###
