"""expand candidate ai fields

Revision ID: 1b18568e035d
Revises: a47617263d92
Create Date: 2026-03-14 15:10:55.918875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b18568e035d'
down_revision: Union[str, None] = 'a47617263d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('linkedin_raw_text', sa.Text(), nullable=True),
    sa.Column('current_title', sa.String(), nullable=True),
    sa.Column('current_company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_career_level', sa.String(), nullable=True),
    sa.Column('ai_outreach_message', sa.Text(), nullable=True),
    sa.Column('ai_parsed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_experience', sa.Text(), nullable=True),
    sa.Column('ai_education', sa.Text(), nullable=True),
    sa.Column('ai_certifications', sa.Text(), nullable=True),
    sa.Column('ai_skills', sa.JSON(), nullable=True),
    sa.Column('ai_years_experience', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('employer_profile_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employer_profile_id'], ['employer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_orders')
    op.drop_table('candidates')
    # ### end Alembic commands ###
