"""add_booking_type_nullable_employer

Revision ID: 2602a0351c01
Revises: 62e1bb17c521
Create Date: 2026-03-06 03:28:16.968239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2602a0351c01'
down_revision: Union[str, None] = '62e1bb17c521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_type', sa.String(length=30), nullable=False))
    op.alter_column('bookings', 'employer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'employer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bookings', 'booking_type')
    # ### end Alembic commands ###
