"""add photo_url banner_url to candidates

Revision ID: 3af477b032b5
Revises: 957289612b32
Create Date: 2026-04-28 04:32:09.615981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af477b032b5'
down_revision: Union[str, None] = '957289612b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('banner_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'banner_url')
    op.drop_column('candidates', 'photo_url')
    # ### end Alembic commands ###
