"""create webhook_logs table

Revision ID: 46a2f9a418dc
Revises: 65707e786c23
Create Date: 2026-03-24 03:16:21.542024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a2f9a418dc'
down_revision: Union[str, None] = '65707e786c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('meeting_id', sa.String(length=50), nullable=True),
    sa.Column('meeting_uuid', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('booking_found', sa.String(length=10), nullable=True),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_event'), 'webhook_logs', ['event'], unique=False)
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_meeting_id'), 'webhook_logs', ['meeting_id'], unique=False)
    op.drop_constraint('fk_bookings_candidate_id', 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'candidate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_bookings_candidate_id', 'bookings', 'candidates', ['candidate_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_webhook_logs_meeting_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_event'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    # ### end Alembic commands ###
