"""added admin email to tenant table

Revision ID: 47aab21e436b
Revises: 177eb717f656
Create Date: 2026-06-25 04:54:46.040927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47aab21e436b'
down_revision: Union[str, None] = '177eb717f656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('admin_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'admin_email')
    # ### end Alembic commands ###
