"""add employer_profiles table

Revision ID: 5b42601b1455
Revises: f64b0fe96265
Create Date: 2026-02-27 03:21:37.413541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b42601b1455'
down_revision: Union[str, None] = 'f64b0fe96265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('ai_industry', sa.String(length=255), nullable=True),
    sa.Column('ai_company_size', sa.String(length=100), nullable=True),
    sa.Column('ai_company_overview', sa.Text(), nullable=True),
    sa.Column('ai_hiring_needs', sa.Text(), nullable=True),
    sa.Column('ai_talking_points', sa.Text(), nullable=True),
    sa.Column('ai_red_flags', sa.Text(), nullable=True),
    sa.Column('ai_brief_raw', sa.Text(), nullable=True),
    sa.Column('ai_brief_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recruiter_notes', sa.Text(), nullable=True),
    sa.Column('relationship_status', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_profiles_company_name'), 'employer_profiles', ['company_name'], unique=False)
    op.create_index(op.f('ix_employer_profiles_id'), 'employer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_employer_profiles_tenant_id'), 'employer_profiles', ['tenant_id'], unique=False)
    op.add_column('bookings', sa.Column('employer_profile_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('call_outcome', sa.String(length=50), nullable=True))
    op.add_column('bookings', sa.Column('call_notes', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('meeting_summary', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'employer_profiles', ['employer_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'meeting_summary')
    op.drop_column('bookings', 'reminded_at')
    op.drop_column('bookings', 'call_notes')
    op.drop_column('bookings', 'call_outcome')
    op.drop_column('bookings', 'employer_profile_id')
    op.drop_index(op.f('ix_employer_profiles_tenant_id'), table_name='employer_profiles')
    op.drop_index(op.f('ix_employer_profiles_id'), table_name='employer_profiles')
    op.drop_index(op.f('ix_employer_profiles_company_name'), table_name='employer_profiles')
    op.drop_table('employer_profiles')
    # ### end Alembic commands ###
