"""add waitlist intent

Revision ID: 62e1bb17c521
Revises: 92a9adbd0df3
Create Date: 2026-03-05 05:15:26.467459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e1bb17c521'
down_revision: Union[str, None] = '92a9adbd0df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist', sa.Column('intent', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waitlist', 'intent')
    # ### end Alembic commands ###
