"""add company_name and website_url to bookings

Revision ID: 6f53ed7d87c7
Revises: ac622688c491
Create Date: 2026-02-20 04:09:55.888340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f53ed7d87c7'
down_revision: Union[str, None] = 'ac622688c491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('website_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'website_url')
    # ### end Alembic commands ###
