"""add response_token to bookings

Revision ID: 85a278165077
Revises: 2602a0351c01
Create Date: 2026-03-09 18:07:27.363246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a278165077'
down_revision: Union[str, None] = '2602a0351c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('response_token', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'response_token')
    # ### end Alembic commands ###
