"""ep18_candidates_booking_id

Revision ID: 8bad52f7eb0f
Revises: 31bc4d401f23
Create Date: 2026-04-07 03:46:08.975834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bad52f7eb0f'
down_revision: Union[str, None] = '31bc4d401f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_candidates_booking_id'), 'candidates', ['booking_id'], unique=False)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_foreign_key(None, 'candidates', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_booking_id'), table_name='candidates')
    op.drop_column('candidates', 'booking_id')
    # ### end Alembic commands ###
