"""add job_interests table

Revision ID: ad0e898204e5
Revises: 061c54194432
Create Date: 2026-07-21 09:42:39.099082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0e898204e5'
down_revision: Union[str, None] = '061c54194432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.Column('job_order_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_order_id', 'candidate_id', name='uq_job_interest_job_candidate')
    )
    op.create_index(op.f('ix_job_interests_id'), 'job_interests', ['id'], unique=False)
    op.create_index(op.f('ix_job_interests_tenant_id'), 'job_interests', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_interests_tenant_id'), table_name='job_interests')
    op.drop_index(op.f('ix_job_interests_id'), table_name='job_interests')
    op.drop_table('job_interests')
    # ### end Alembic commands ###
