"""add_rich_meeting_fields

Revision ID: c320b5d1795c
Revises: 3b1bb86413d5
Create Date: 2026-03-18 08:36:48.086655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c320b5d1795c'
down_revision: Union[str, None] = '3b1bb86413d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('meeting_next_steps', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('meeting_keywords', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('meeting_transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'meeting_transcript')
    op.drop_column('bookings', 'meeting_keywords')
    op.drop_column('bookings', 'meeting_next_steps')
    # ### end Alembic commands ###
