"""add employer_profile_id and outcome fields to bookings

Revision ID: f5148a91a459
Revises: 5b42601b1455
Create Date: 2026-02-27 03:21:54.464336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5148a91a459'
down_revision: Union[str, None] = '5b42601b1455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
